# Generated by Django 3.1.1 on 2020-09-30 21:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
